### ISSUE TITLE
Design monster detection system

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/uss-meme#1]
We intend to design a monster detection system. Using motion detectors, we want to implement the following layers:

**Layer 1:** On monster detection, lock doors in range of the detector and change lights to red. Maintain this state until the monster is no longer detected

**Layer 2:** On monster detection, send a signal to a Wi-Fi component in the security area, which sends a message to text chat about where the monster is located. I believe this can be accomplished with a concatenator and Wi-Fi component. The message should only be sent once each time the monster is detected.

A reproducible circuit should be designed for each phase, and then we should create a list of rooms to implement the circuits in order of priority. We'll generate new tasks for each of these rooms.

**Comment by pfrissora** [comment]
For layer 1, how will we kill the monster if it's behind a locked door?

**Comment by super-cooper** [comment]
> For layer 1, how will we kill the monster if it's behind a locked door?

The state of the door is only set at the exact moment the motion detector sees a monster, so you should be able to just press the button from the outside to open the door.
